<a href="https://colab.research.google.com/github/Pepcoders/Data-Science-December/blob/main/NLP/Fake_News_Classifier_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd


In [2]:
df=pd.read_csv('/content/drive/MyDrive/fake-news/fake_train.csv')

In [3]:
df=df.dropna()

In [4]:
X=df.drop('label',axis=1)

In [5]:
y=df['label']

In [6]:
import tensorflow as tf

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [8]:
voc_size=5000

In [14]:
messages = X.copy()

messages.reset_index(inplace=True)

In [15]:
import nltk
import re
from nltk.corpus import stopwords

In [16]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [17]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [18]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [19]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[75, 607, 1056, 2344, 2054, 3541, 2268, 2201, 3797, 2442],
 [2878, 2510, 2696, 831, 2400, 1559, 473],
 [3399, 2159, 821, 3042],
 [4476, 2867, 2980, 2037, 185, 3049],
 [1846, 2400, 3124, 2716, 2229, 1558, 2400, 2775, 1055, 610],
 [1469,
  498,
  2264,
  1661,
  4249,
  1785,
  4302,
  2039,
  3985,
  616,
  4622,
  776,
  310,
  2100,
  473],
 [4791, 3803, 4839, 305, 1218, 2985, 69, 1878, 1907, 3971, 2434],
 [3967, 2490, 3840, 4029, 4428, 1190, 1785, 602, 1907, 3971, 2434],
 [1880, 4864, 4947, 2012, 1875, 749, 407, 1072, 1785, 2974],
 [2701, 22, 1805, 805, 3819, 3366, 2979, 2540],
 [1012, 4525, 2837, 2005, 294, 955, 942, 3900, 120, 4618, 2320],
 [2037, 886, 2054, 749, 1785, 4428],
 [3707, 874, 989, 3307, 4144, 3705, 4174, 608, 1069],
 [2767, 386, 94, 497, 1500, 2960, 3243, 1907, 3971, 2434],
 [1631, 4362, 3526, 4108, 4256, 1907, 3971, 2434],
 [1856, 2582, 2150, 1141, 1006, 1928, 2864, 3011, 1908, 3539],
 [282, 2833, 2510],
 [1257, 3053, 931, 440, 1785, 444, 4202, 473],
 [1154, 2754, 26

In [20]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 2201 3797 2442]
 [   0    0    0 ... 2400 1559  473]
 [   0    0    0 ... 2159  821 3042]
 ...
 [   0    0    0 ... 1907 3971 2434]
 [   0    0    0 ... 4571  390 4903]
 [   0    0    0 ... 4291 3481 4233]]


In [21]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,   75,
        607, 1056, 2344, 2054, 3541, 2268, 2201, 3797, 2442], dtype=int32)

In [30]:
## Creating model
from tensorflow.keras.layers import Dropout

embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.4))
#model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 20, 40)            200000    
                                                                 
 dropout (Dropout)           (None, 20, 40)            0         
                                                                 
 lstm_5 (LSTM)               (None, 100)               56400     
                                                                 
 dropout_1 (Dropout)         (None, 100)               0         
                                                                 
 dense_1 (Dense)             (None, 1)                 101       
                                                                 
Total params: 256,501
Trainable params: 256,501
Non-trainable params: 0
_________________________________________________________________
None


In [31]:
len(embedded_docs),y.shape

(18285, (18285,))

In [32]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

In [34]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
192/192 [==============================] - 6s 25ms/step - loss: 0.3591 - accuracy: 0.8371 - val_loss: 0.2013 - val_accuracy: 0.9137
Epoch 2/10
192/192 [==============================] - 4s 22ms/step - loss: 0.1521 - accuracy: 0.9415 - val_loss: 0.1888 - val_accuracy: 0.9241
Epoch 3/10
192/192 [==============================] - 4s 23ms/step - loss: 0.1117 - accuracy: 0.9585 - val_loss: 0.1977 - val_accuracy: 0.9223
Epoch 4/10
192/192 [==============================] - 4s 23ms/step - loss: 0.0882 - accuracy: 0.9693 - val_loss: 0.2206 - val_accuracy: 0.9171
Epoch 5/10
192/192 [==============================] - 4s 22ms/step - loss: 0.0687 - accuracy: 0.9749 - val_loss: 0.2301 - val_accuracy: 0.9171
Epoch 6/10
192/192 [==============================] - 4s 23ms/step - loss: 0.0460 - accuracy: 0.9836 - val_loss: 0.3026 - val_accuracy: 0.9158
Epoch 7/10
192/192 [==============================] - 4s 23ms/step - loss: 0.0387 - accuracy: 0.9872 - val_loss: 0.3332 - val_accuracy: 0.9193